<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.82.0">
  <title>Support user dashboard</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

  <!-- Bootstrap core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <script src="Scripts/handlebars-v4.7.7.js"></script>
  <script src="Scripts/jquery.min.js" type="text/javascript"></script>
  <script src="Scripts/jquery-1.7.1.js" type="text/javascript"></script>


  <script src="Scripts/jquery.signalR-2.2.0.js"></script>
  <!--Reference the autogenerated SignalR hub script. -->
  <script src="signalr/hubs"></script>

 


  <!-- Custom styles for this template -->
  <link href="css/admin/dashboard.css" rel="stylesheet">
</head>

<body >
  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" >Hts</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link logout" href=""><span data-feather="log-out"></span> Sign out</span></a>
      </li>
    </ul>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse" >
        <div class="position-sticky pt-3" >

          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page">
                <span data-feather="home"></span>
                Dashboard
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link">
                <span data-feather="file"></span>
                 Assigned complaints
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" >
                <span data-feather="shopping-cart"></span>
                Products
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" >
                <span data-feather="users"></span>
                Customers
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" >
                <span data-feather="bar-chart-2"></span>
                Reports
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link">
                <span data-feather="layers"></span>
                Integrations
              </a>
            </li>

          </ul>

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="link-secondary"  aria-label="Add a new report">
              <span data-feather="plus-circle"></span>
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" >
                <span data-feather="file-text"></span>
                Current month
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" >
                <span data-feather="file-text"></span>
                Last quarter
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" >
                <span data-feather="file-text"></span>
                Social engagement
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" >
                <span data-feather="file-text"></span>
                Year-end sale
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Support / developer user dashboard</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
              <span data-feather="calendar"></span>
              <select class="form-select">
                <option>Request status ... </option>
                <option>Pending</option>
                <option>On-hold</option>
                <option>Customer reply</option>
                <option>Answered</option>
              </select>

          </div>
        </div>

          <div class="container">
            <div class="table-responsive" id="">
              <div class="card" id="request-area"></div>
              <script id="table" type="text/x-handlebars">
                <table class="table table-striped" >
                  <thead>
                    <tr style="background-color:#092756; color:white;">
                      <th>COMPLAINT ID</th>
                      <th>CUSTOMER NAME</th>
                      <th>COMPLAINT MESSAGE</th>
                      <th>REQUEST STATUS</th>
                      <th>LOGGED REQUEST DATE</th>
                    </tr>
                  </thead>
                <tbody>
                    {{#each request}}
                      <tr style="margin-top:10px;">
                        <td>{{COMPLAINT_ID}}</td>
                        <td>{{CUSTOMER_NAME}}</td>
                        <td>{{REQUEST}}</td>
                        <td name = "status-name">{{STATUS_NAME}}</td>
                        <td>{{formatDate DATE_CREATED}}</td>
                      </tr>
                    {{/each}}
                  </tbody>
              </table>
            </script>
            </div>
          </div>

      </main>
    </div>
  </div>

  <script src="pages/general.js"></script>
<script src="pages/users/user.js"></script>
<script src="pages/admin/hide-show-functions.js"></script>
<script src="scripts/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
    integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
    crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/@myspace-nu/jquery.fancytable/dist/fancyTable.min.js"></script>


    <script>
      Handlebars.registerHelper('formatDate', function (date) {
        return new Date(date).toDateString();
      })
    </script>


  <script type="text/javascript">   
    $(document).ready(function() {
      $(".table").fancyTable({
      /* Column number for initial sorting*/
        sortColumn:0,
        /* Setting pagination or enabling */
        pagination: true,
        /* Rows per page kept for display */
        perPage:3,
        globalSearch:true
        });                    
    });
</script>


</body>

</html>