<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>customer dashboard</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">



    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <script src="Scripts/handlebars-v4.7.7.js"></script>
    <script src="Scripts/jquery.min.js" type="text/javascript"></script>
    <script src="Scripts/jquery-1.7.1.js" type="text/javascript"></script>


    <script src="Scripts/jquery.signalR-2.2.0.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>

    <!-- Custom styles for this template -->

    <link href="css/admin/dashboard.css" rel="stylesheet">
</head>

<body>
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">High Tech Synegy</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" id="myInput"
        aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap loggedname">
            
        </li>
    </ul>
</header>

<div class="container-fluid" style="margin-top: 50px;">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">

                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" id="dash">
                            <span data-feather="home"></span>
                            Customer user
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="customer-logs">
                            <span data-feather="activity"></span>
                            Logged complaints
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="user-list-show">
                            <span data-feather="layers"></span>
                            Rate Complaint
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link logout" id="user-list-show">
                            <span data-feather="layers"></span>
                            Sign out
                        </a>
                    </li>

                </ul>

            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="container" id="user_complaint_table">
                <div class="table-responsive" id="log-table">
                    <div class="card" id="request-area"></div>
                    <script id="table" type="text/x-handlebars">
                    <table class="table table-striped" id="log-table">
                        <thead>
                        <tr style="background-color:#092756; color:white;">
                            <th>COMPLAINT ID</th>
                            <th>CUSTOMER NAME</th>
                            <th>COMPLAINT MESSAGE</th>
                            <th>REQUEST STATUS</th>
                            <th>LOGGED REQUEST DATE</th>
                          
                        </tr>
                        </thead>
                    <tbody>
                        {{#each request}}
                            <tr style="margin-top:10px;">
                            <td>{{COMPLAINT_ID}}</td>
                            <td>{{CUSTOMER_NAME}}</td>
                            <td>{{REQUEST}}</td>
                            <td name = "status-name">{{STATUS_NAME}}</td>
                            <td>{{formatDate DATE_CREATED}}</td>
                            </tr>
                        {{/each}}
                        </tbody>
                    </table>
                </script>
                </div>
            </div>

            <!--   Form used to add a complaint category to the back-end -->
            <div id="complaint-create-form">
                <label for="complaintInputName" class="form-label">Make a complaint </label>
                <div id="category-display-part"></div>
                <br/>
                <div class="mb-3">
                 
                    <textarea name="CATEGORY" class="form-control" placeholder="Type complaint here.." id="complaintInputName" style="height:200px;"
                        aria-describedby="emailHelp"></textarea>
                </div>

                <script type="text/x-handlebars" id="categorytemplate">
                                        <select class="form-control" id="category">
                                            <option value="">Select Category</option>
                                            {{#each complaint_category}}
                                            <option  value="{{CATEGORY_ID}}">{{CATEGORY}}</option>
                                            {{/each}}
                                            </select>
                                        </script>

                <button type="button" class="btn btn-danger" id="assign-category-btn"> Submit</button>

            </div>

            <!-- HandleBars table that performs task of creating a table that contains fetched records from database -->

            
  

        </main>

    </div>
</div>



<script src="pages/customers/customer.js"></script>
<script src="pages/admin/hide-show-functions.js"></script>
<script src="scripts/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
    integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
    crossorigin="anonymous"></script>

<script src="pages/general.js"></script>


<script>
    Handlebars.registerHelper('formatDate', function (date) {
        return new Date(date).toDateString();
    })
</script>

</body>

</html>