<!DOCTYPE html>
<html>

<head>
  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">



  <title>Login page</title>

  <link rel="stylesheet" href="pages/signin/signin.css">
</head>

<body>
  <div class="login">
    <h1 style="margin-bottom:20px;">Login</h1>
    <div id="log-form-id">
      <input type="text" name="USERMAIL" placeholder="Username" required="required" id="user" />
      <input type="password" name="PASSWORD" placeholder="Password" required="required" id="pass" />
      <button type="button" class="btn btn-primary btn-block btn-large logbtn">Let me in.</button>
    </div>
  </div>

   <div id="success-message"
      style="background-color: lightgreen; padding-top: 5px; padding-bottom: 5px; padding-right:5px; padding-left: 5px; width: 50%;">
      Authentication successful !
    </div>


  <script src="Scripts/jquery.min.js" type="text/javascript"></script>
  <script src="Scripts/jquery-1.7.1.js" type="text/javascript"></script>
  <script src="Scripts/jquery.signalR-2.2.0.js"></script>
  <!--Reference the autogenerated SignalR hub script. -->
  <script src="signalr/hubs"></script>
  <!-- Custom styles for this template -->


<script src="pages/signin/signin.js">
</script>
</body>

</html>